<a href="https://colab.research.google.com/github/RameezHiro/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy




# Intro of Numpy

In [ ]:
import numpy as np

array = np.array([1,2,3,4])

array = array * 2

print(array)

print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


# Multidememsional Array



Array Dimension and Shape

In [ ]:
import numpy as np

array = np.array([[['A', 'B', 'C'],['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'],['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'],['V', 'W', 'X'], ['Y', 'Z', ' ']]])

print(array.ndim)
print(array.shape)
print(array[1, 1, 1])

3
(3, 3, 3)
N


Practice

In [ ]:
import numpy as np

array = np.array([[['A', 'B', 'C'],['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'],['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'],['V', 'W', 'X'], ['Y', 'Z', ' ']]])

word = array[0, 0, 2] + array[0, 0, 0] + array[1, 1, 1]

print(word)

CAN


# Slicing

In [14]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0])

[1 2 3 4]


In [15]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[-1])

[13 14 15 16]


In [16]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[1:4])

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

 #array[start:end:step]

print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [18]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [20]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[::-1])


[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[::2])