<a href="https://colab.research.google.com/github/RameezHiro/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy




# Intro of Numpy

In [ ]:
import numpy as np

array = np.array([1,2,3,4])

array = array * 2

print(array)

print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


# Multidememsional Array



Array Dimension and Shape

In [ ]:
import numpy as np

array = np.array([[['A', 'B', 'C'],['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'],['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'],['V', 'W', 'X'], ['Y', 'Z', ' ']]])

print(array.ndim)
print(array.shape)
print(array[1, 1, 1])

3
(3, 3, 3)
N


Practice

In [ ]:
import numpy as np

array = np.array([[['A', 'B', 'C'],['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'],['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'],['V', 'W', 'X'], ['Y', 'Z', ' ']]])

word = array[0, 0, 2] + array[0, 0, 0] + array[1, 1, 1]

print(word)

CAN


# Slicing

In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0])

[1 2 3 4]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[-1])

[13 14 15 16]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[1:4])

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

 #array[start:end:step]

print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[::-1])


[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, 0])

[ 1  5  9 13]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, -1])

[ 4  8 12 16]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, 0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, 1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, 1::2])

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, ::-1])   #It would be in Reverse order

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0:2, 0:2])

[[1 2]
 [5 6]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0:2, 2:])

[[3 4]
 [7 8]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[2:, 0:2])

[[ 9 10]
 [13 14]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[2:, 2:])

[[11 12]
 [15 16]]


# Arithmetic

In [ ]:
import numpy as np

# Scalar arithmetic

array = np.array([1, 2, 3])

print(array + 1)
print(array - 1)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[0 1 2]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
import numpy as np

# Vector maths func

array = np.array([1.01, 2.5, 3.99])

print(np.sqrt(array))

print(np.round(array))

print(np.floor(array))

print(np.ceil(array))

print(np.pi)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [ ]:
import numpy as np

# Excercise

radii = np.array([1, 2, 3])

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


# Element-Wise Arithmetic

In [2]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


# Comparison Operator

In [3]:
import numpy as np

scores = np.array([91,55, 100, 73, 83, 65])

print(scores == 100)
print(scores >= 80)
print(scores >= 60)
print(scores <= 90)
print(scores < 60)

[False False  True False False False]
[ True False  True False  True False]
[ True False  True  True  True  True]
[False  True False  True  True  True]
[False  True False False False False]


# Broadcasting

In [5]:
   # Broadcasting allows numpy to perform  operations on arrays
   # with different shapes by virtually expanding dimensions
   # so they match the larger arrays shape

 # The dimension have he same size
 # OR
 #  One of the dimension has a size of 1

import numpy as np

array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)

print(array2.shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [9]:
import numpy as np

array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])

array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


# Aggregate Function

In [11]:
import numpy as np

array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))

55
5.5
2.8722813232690143
8.25
1
10
0
9


In [12]:
import numpy as np

# Aggregate functions = summarize data and typically returns single value

array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print(np.sum(array, axis=0)) # Sums all the Columns

print(np.sum(array, axis=1)) # Sums all the Rows

[ 7  9 11 13 15]
[15 40]
