<a href="https://colab.research.google.com/github/RameezHiro/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy




# Intro of Numpy

In [ ]:
import numpy as np

array = np.array([1,2,3,4])

array = array * 2

print(array)

print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


# Multidememsional Array



Array Dimension and Shape

In [ ]:
import numpy as np

array = np.array([[['A', 'B', 'C'],['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'],['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'],['V', 'W', 'X'], ['Y', 'Z', ' ']]])

print(array.ndim)
print(array.shape)
print(array[1, 1, 1])

3
(3, 3, 3)
N


Practice

In [ ]:
import numpy as np

array = np.array([[['A', 'B', 'C'],['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'],['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'],['V', 'W', 'X'], ['Y', 'Z', ' ']]])

word = array[0, 0, 2] + array[0, 0, 0] + array[1, 1, 1]

print(word)

CAN


# Slicing

In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0])

[1 2 3 4]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[-1])

[13 14 15 16]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[1:4])

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

 #array[start:end:step]

print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[::-1])


[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [2]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, 0])

[ 1  5  9 13]


In [4]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, -1])

[ 4  8 12 16]


In [5]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, 0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [6]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, 1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [7]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [8]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, 1::2])

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [9]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[:, ::-1])   #It would be in Reverse order

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [11]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0:2, 0:2])

[[1 2]
 [5 6]]


In [12]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[0:2, 2:])

[[3 4]
 [7 8]]


In [13]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[2:, 0:2])

[[ 9 10]
 [13 14]]


In [14]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(array[2:, 2:])

[[11 12]
 [15 16]]


# Arithmetic

In [20]:
import numpy as np

# Scalar arithmetic

array = np.array([1, 2, 3])

print(array + 1)
print(array - 1)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[0 1 2]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [25]:
import numpy as np

# Vector maths func

array = np.array([1.01, 2.5, 3.99])

print(np.sqrt(array))

print(np.round(array))

print(np.floor(array))

print(np.ceil(array))

print(np.pi)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [26]:
import numpy as np

# Excercise

radii = np.array([1, 2, 3])

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]
